version: "3"


services:
  webserver:
    image: nginx:stable-alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d
      - "${PWD-.}/images:/var/www/data/images"
    networks:
      - mind-core

  bentoml:
    image: chanelcolgate/yolo_v8_demo:i6kbkuoxostnirek
    restart: always
    user: root
    hostname: bentoml
    ports:
      - "3000:3000"
    environment:
      - HF_MODEL_ID=chanelcolgate/chamdiemgianhang-vsk
      - MODEL_CONF=0.5
      - MODEL_IOU=0.45
    volumes:
      - "${PWD-.}/images:/tmp/images"
    networks:
      - mind-core

  db:
    image: postgres:13
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata
      - "${PWD-.}/datasets:/docker-entrypoint-initdb.d"
    networks:
      - mind-core

  adminer:
    image: adminer
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - mind-core

  rabbitmq:
    image: rabbitmq:3.12-management
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-db:/var/lib/rabbitmq
    networks:
      - mind-core


  declare:
    image: chanelcolgate/backend:b0c5ab5b282ee327a628517cd989fbf5c4ffc38d
    restart: always
    command: "declare_rabbitmq.py"
    environment:
      # DEBUG: false
      DATABASE_HOST: db
      DATABASE_URL: postgres://odoo:odoo@db:5432/vsk
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/%2F
      # SHOW: true
      LIMIT: 300
    depends_on:
      - db
      - rabbitmq
    networks:
      - mind-core


  worker:
    image: chanelcolgate/backend:b0c5ab5b282ee327a628517cd989fbf5c4ffc38d
    restart: always
    command: "worker.py"
    environment:
      # DEBUG: false
      DATABASE_HOST: db
      DATABASE_URL: postgres://odoo:odoo@db:5432/vsk
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/%2F
      BENTOML_URL: http://bentoml:3000/render
      # SHOW: true
      LIMIT: 300
    depends_on:
      - db
      - rabbitmq
      # - declare
    networks:
      - mind-core


  main:
    image: chanelcolgate/backend:b0c5ab5b282ee327a628517cd989fbf5c4ffc38d
    restart: always
    container_name: main
    command: "main.py"
    ports:
      - "8000:8000"
    volumes:
      - "${PWD-.}/images:/app/src/images"
      - "${PWD-.}/tmp:/app/src/tmp"
      - "${PWD-.}/authorized:/app/src/authorized"
    environment:
      # DEBUG: true
      DATABASE_HOST: db
      DATABASE_URL: postgres://odoo:odoo@db:5432/vsk
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/%2F
      # SHOW: true
      LIMIT: 300
      AUTHORIZED_PATH: authorized.json
      FTP_URL: http://10.17.4.72/raw
    depends_on:
      - db
      - rabbitmq
    networks:
      - mind-core


volumes:
  db-data:
  rabbitmq-db:


networks:
  mind-core: