version: "3.8"
services:
  bentoml:
    image: chanelcolgate/yolo_v8_demo:wrkvtqv5coqvbuy3
    hostname: bentoml
    ports:
      - "3000:3000"
    volumes:
      - ./backend/src/images:/tmp/images
    networks:
      - label_studio_network

  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata
      - "./datasets:/docker-entrypoint-initdb.d"
    networks:
      - label_studio_network

  adminer:
    image: adminer
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - label_studio_network

  rabbitmq:
    image: rabbitmq:3.12-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-db:/var/lib/rabbitmq
    networks:
      - label_studio_network


  declare:
    image: chanelcolgate/backend:5f3e0ce67605a91b6a0d11b0c04a95eca30fe3e1
    container_name: declare
    command: "declare_rabbitmq.py"
    environment:
      DEBUG: false
      DATABASE_HOST: db
      DATABASE_URL: postgres://odoo:odoo@db:5432/vsk
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/%2F
      SHOW: true
      LIMIT: 300
    depends_on:
      - db
      - rabbitmq
    networks:
      - label_studio_network


  worker:
    image: chanelcolgate/backend:5f3e0ce67605a91b6a0d11b0c04a95eca30fe3e1
    container_name: worker
    restart: always
    command: "worker.py"
    environment:
      DEBUG: false
      DATABASE_HOST: db
      DATABASE_URL: postgres://odoo:odoo@db:5432/vsk
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/%2F
      BENTOML_URL: http://bentoml:3000/render
      SHOW: true
      LIMIT: 300
    depends_on:
      - db
      - rabbitmq
    networks:
      - label_studio_network


  main:
    image: chanelcolgate/backend:5f3e0ce67605a91b6a0d11b0c04a95eca30fe3e1
    container_name: main
    command: "main.py"
    ports:
      - "8000:8000"
    volumes:
      - "${PWD-.}/backend/src/images:/app/src/images"
      - "${PWD-}./backend/src/tmp:/app/src/tmp"
    environment:
      DEBUG: true
      DATABASE_HOST: db
      DATABASE_URL: postgres://odoo:odoo@db:5432/vsk
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/%2F
      SHOW: true
      LIMIT: 300
    depends_on:
      - db
      - rabbitmq
    networks:
      - label_studio_network


volumes:
  db-data:
  rabbitmq-db:

networks:
  label_studio_network:
