version: "3.8"

services:
  redis:
    image: redis:alpine
    hostname: redis
    volumes:
      - "./data/redis:/data"
    expose:
      - 6379
  server:
    build: .
    environment:
      - RQ_QUEUE_NAME=default
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - "9092:9090"
    depends_on:
      - redis
    links:
      - redis
    volumes:
      - "./logs:/tmp"
      - "D:/programming/Machine Learning in Production/label-studio-2/mydata/media/:/data"
